import random

_SAFE_SUBJECTS = [
    "Liam",
    "Noah",
    "Oliver",
    "Elijah",
    "James",
    "William",
    "Benjamin",
    "Lucas",
    "Henry",
    "Alexander",
    "Daniel",
    "Michael",
    "Ethan",
    "Jacob",
    "Logan",
    "Jackson",
    "Aiden",
    "Matthew",
    "Leo",
    "Sebastian",
    "Olivia",
    "Emma",
    "Ava",
    "Sophia",
    "Isabella",
    "Mia",
    "Amelia",
    "Harper",
    "Evelyn",
    "Abigail",
    "Emily",
    "Ella",
    "Elizabeth",
    "Camila",
    "Luna",
    "Sofia",
    "Avery",
    "Mila",
    "Aria",
    "Scarlett",
    "Alex",
    "Taylor",
    "Jordan",
    "Casey",
    "Riley",
    "Morgan",
    "Quinn",
    "Skyler",
    "Rowan",
    "Hayden",
    "Reese",
    "Dakota",
    "Finley",
    "Jamie",
    "Kai",
    "River",
    "Sage",
    "Charlie",
    "Emerson",
    "The father",
    "The mother",
    "The parent",
    "The son",
    "The daughter",
    "The child",
    "The cousin",
    "The aunt",
    "The uncle",
    "The niece",
    "The nephew",
    "The sibling",
    "The grandparent",
    "The grandfather",
    "The grandmother",
    "The parents",
    "The children",
    "The cousins",
    "The siblings",
    "The grandparents",
    "The teacher",
    "The student",
    "The engineer",
    "The doctor",
    "The nurse",
    "The driver",
    "The artist",
    "The chef",
    "The baker",
    "The farmer",
    "The carpenter",
    "The plumber",
    "The electrician",
    "The designer",
    "The writer",
    "The singer",
    "The dancer",
    "The firefighter",
    "The police officer",
    "The developer",
    "The scientist",
    "The pilot",
    "The waiter",
    "The cashier",
    "The coach",
    "The teachers",
    "The students",
    "The engineers",
    "The doctors",
    "The nurses",
    "The drivers",
    "The artists",
    "The chefs",
    "The bakers",
    "The farmers",
    "The carpenters",
    "The plumbers",
    "The electricians",
    "The designers",
    "The writers",
    "The singers",
    "The dancers",
    "The firefighters",
    "The police officers",
    "The developers",
    "The scientists",
    "The pilots",
    "The waiters",
    "The cashiers",
    "The coaches",
    "The cat",
    "The dog",
    "The bird",
    "The rabbit",
    "The horse",
    "The cow",
    "The sheep",
    "The duck",
    "The turtle",
    "The fox",
    "The lion",
    "The tiger",
    "The bear",
    "The panda",
    "The dolphin",
    "The whale",
    "The cats",
    "The dogs",
    "The birds",
    "The rabbits",
    "The horses",
    "The cows",
    "The ducks",
    "The turtles",
    "The foxes",
    "The lions",
    "The tigers",
    "The bears",
    "The pandas",
    "The dolphins",
    "The whales",
]

_SAFE_ADVERBS  = ["", "", "", "today", "now", "slowly", "quickly", "carefully", "together"]

_OBJ = {
    "food_eat":   ["bread","rice","an apple","a sandwich","dinner","lunch","breakfast","a meal"],
    "food_drink": ["water","coffee","tea","milk","juice","soup"],
    "food_cook":  ["dinner","rice","a meal","soup","eggs"],

    "thing_open":  ["the door","the window","a box","a bag","a book"],
    "thing_close": ["the door","the window","a box","a bag","a book"],
    "thing_use":   ["a phone","a computer","a pen","a chair","a light"],

    "reading": ["a book","the news","a story","a text message"],
    "media":   ["a movie","a video","music","a song"],

    "place":  ["home","school","work","the store","the park","the room","the kitchen","the bus stop"],
    "person": ["a friend","my friend","the teacher","the doctor","the family","my family"],
    "task":   ["homework","a message","a note","a call"],

    "vehicle": ["a car","the car"]
}

_COMPAT = {
    "eat":       ["food_eat"],
    "drink":     ["food_drink"],
    "cook":      ["food_cook"],
    "make":      ["food_cook","task","thing_use"],
    "have":      ["food_eat","food_drink","a rest","a break","a shower"],
    "get":       ["thing_use","food_eat","task"],
    "buy":       ["thing_use","food_eat"],
    "bring":     ["thing_use","food_eat"],
    "open":      ["thing_open"],
    "close":     ["thing_close"],
    "use":       ["thing_use"],
    "read":      ["reading"],            
    "watch":     ["media"],              
    "play":      ["media","a game"],     
    "listen to": ["media"],              
    "write":     ["task","a note"],      
    "send":      ["task"],               
    "call":      ["person"],
    "help":      ["person"],
    "meet":      ["person"],
    "visit":     ["person","place"],
    "clean":     ["thing_use","place","the room","the kitchen"],
    "find":      ["thing_use"],
    "need":      ["thing_use","food_eat","help"],
    "like":      ["thing_use","food_eat","media","place"],
    "love":      ["thing_use","food_eat","media","place","my family"],
    "go to":     ["place"],
    "come to":   ["place"],
    "walk to":   ["place"],
    "study":     ["English","math","science"],
    "work":      [""],    
    "sleep":     [""],    
    "drive":     ["vehicle"],
}

VERBS = ["eat","drink","cook","make","have","get","buy","bring","open","close",
             "use","read","watch","play","listen to","write","send","call","help",
             "meet","visit","clean","find","need","like","love","go to","come to",
             "walk to","study","work","sleep","drive"]

def _choose_object_for(verb, rng):
    pools = _COMPAT.get(verb, ["thing_use"])
    choice = rng.choice(pools)
    lst = _OBJ.get(choice)
    return rng.choice(lst) if lst else choice

def _cap(s): 
    return s[:1].upper() + s[1:] if s else s

def generate_sentence_beginner(seed=None):
    rng = random.Random(seed)

    subj = rng.choice(_SAFE_SUBJECTS)
    vb   = rng.choice(VERBS)
    adv  = rng.choice(_SAFE_ADVERBS)
    obj = _choose_object_for(vb, rng)
    
    vp = f"can {vb}" + (f" {obj}" if obj else "")
    if adv:
        vp = (f"{vp} {adv}") if adv in {"today","now"} else vp.replace("can ", f"can {adv} ", 1)

    vp = vp.replace(" to the home", " home").replace(" to home", " home")
    return f"{_cap(subj)} {vp}."

SUJETOS = [
    "Father",
    "Mother",
    "Parent",
    "Son",
    "Daughter",
    "Child",
    "Cousin",
    "Aunt",
    "Uncle",
    "Niece",
    "Nephew",
    "Sibling",
    "Grandparent",
    "Grandfather",
    "Grandmother",
    "Teacher",
    "Student",
    "Engineer",
    "Doctor",
    "Nurse",
    "Driver",
    "Artist",
    "Chef",
    "Baker",
    "Farmer",
    "Carpenter",
    "Plumber",
    "Electrician",
    "Designer",
    "Writer",
    "Singer",
    "Dancer",
    "Firefighter",
    "Police officer",
    "Developer",
    "Scientist",
    "Pilot",
    "Waiter",
    "Cashier",
    "Coach",
    "Cat",
    "Dog",
    "Bird",
    "Rabbit",
    "Horse",
    "Cow",
    "Sheep",
    "Duck",
    "Turtle",
    "Fox",
    "Lion",
    "Tiger",
    "Bear",
    "Panda",
    "Dolphin",
    "Whale",
]

VERBOS = ["Eat","Drink","Cook","Make","Have","Get","Buy","Bring","Open","Close",
             "Use","Read","Watch","Play","Listen","Write","Send","Call","Help",
             "Meet","Visit","Clean","Find","Need","Like","Love","Go","Come",
             "Walk","Study","Work","Sleep","Drive"]

COLORES = [
    "Red",
    "Blue",
    "Green",
    "Yellow",
    "Black",
    "White",
    "Orange",
    "Purple",
    "Pink",
    "Brown",
    "Gray",
    "Cyan",
    "Magenta",
    "Beige",
    "Violet",
    "Gold",
    "Silver",
    "Turquoise",
    "Maroon",
    "Navy",
    "Olive",
    "Teal",
    "Indigo",
    "Lavender",
    "Coral",
    "Peach",
    "Tan",
    "Mint",
    "Burgundy",
    "Ivory",
]

FAMILIA = [
    "Father",
    "Mother",
    "Parent",
    "Son",
    "Daughter",
    "Child",
    "Brother",
    "Sister",
    "Grandfather",
    "Grandmother",
    "Grandparent",
    "Uncle",
    "Aunt",
    "Cousin",
    "Nephew",
    "Niece",
    "Husband",
    "Wife",
    "Partner",
    "Relative",
    "Stepfather",
    "Stepmother",
    "Stepson",
    "Stepdaughter",
    "Half brother",
    "Half sister",
    "Father-in-law",
    "Mother-in-law",
    "Son-in-law",
    "Daughter-in-law",
    "Brother-in-law",
    "Sister-in-law",
]

ADJETIVOS = [
    "Big",
    "Small",
    "Tall",
    "Short",
    "Long",
    "Young",
    "Old",
    "New",
    "Good",
    "Bad",
    "Sad",
    "Beautiful",
    "Ugly",
    "Hot",
    "Cold",
    "Warm",
    "Cool",
    "Fast",
    "Slow",
    "Easy",
    "Difficult",
    "Hard",
    "Soft",
    "Strong",
    "Weak",
    "Clean",
    "Dirty",
    "Full",
    "Empty",
    "Expensive",
    "Cheap",
    "Funny",
    "Serious",
    "Kind",
    "Rude",
    "Friendly",
    "Angry",
    "Tired",
    "Hungry",
    "Thirsty",
    "Busy",
    "Free",
    "Quiet",
    "Noisy",
    "Early",
    "Late",
    "Rich",
    "Poor",
    "Smart",
    "Stupid",
    "Delicious",
    "Boring",
    "Interesting",
    "Famous",
    "Important",
    "Happy",
    "Lovely",
    "Nice",
    "Polite",
    "Brave",
    "Lazy",
]

LUGARES = [
  "the bathroom",
  "the restroom",
  "the toilet",
  "the airport",
  "the train station",
  "the bus station",
  "the bus stop",
  "the subway station",
  "the metro station",
  "the taxi stand",
  "the hotel",
  "the hostel",
  "the reception",
  "the front desk",
  "the information desk",
  "the tourist information center",
  "the embassy",
  "the consulate",
  "the police station",
  "the hospital",
  "the clinic",
  "the pharmacy",
  "the dentist",
  "the doctor",
  "the library",
  "the museum",
  "the art gallery",
  "the theater",
  "the cinema",
  "the park",
  "the playground",
  "the stadium",
  "the beach",
  "the bank",
  "the ATM",
  "the supermarket",
  "the grocery store",
  "the convenience store",
  "the bakery",
  "the butcher",
  "the market",
  "the shopping mall",
  "the department store",
  "the post office",
  "the city hall",
  "the courthouse",
  "the university",
  "the school",
  "the classroom",
  "the cafeteria",
  "the restaurant",
  "the café",
  "the bar",
  "the parking lot",
  "the gas station",
  "the charging station",
  "the car rental",
  "the entrance",
  "the exit",
  "the elevator",
  "the stairs",
  "the escalator",
  "the ticket office",
  "the boarding gate",
  "the baggage claim",
  "the security checkpoint",
  "the customs",
  "the immigration",
  "the locker",
  "the left-luggage office",
  "the meeting point",
  "the viewpoint",
  "the bridge",
  "the river",
  "the cathedral",
  "the church",
  "the mosque",
  "the temple",
  "the synagogue",
  "the zoo",
  "the aquarium",
  "the amusement park",
  "the campsite",
  "the pharmacy counter",
  "the laundry",
  "the hair salon",
  "the barbershop",
  "the spa",
  "the gym"
];

def conseguirPalabraRandom(categoria: str) -> str:
    match categoria:
        case "sujeto":
            return random.choice(SUJETOS)
        case "verbo":
            return random.choice(VERBOS)
        case "color":
            return random.choice(COLORES)
        case "familia":
            return random.choice(FAMILIA)
        case "adjetivo":
            return random.choice(ADJETIVOS)
        case "direccion":
            return f"Where is {random.choice(LUGARES)}?"
        case _:
            return ""